### ISSUE TITLE
automatically add group derived from elfeed-org

### ISSUE THREAD

**Issue by jarifuri** [SqrtMinusOne/elfeed-summary#6]
I started to use the elfeed-summary and noticed that the my groups were the same as the tags I defined via the elfeed-org.

Just for the purpose of laziness, it would be nice to have some way which automatically derives the structure of elfeed-org file (probably only the tags as the structure of the org file could have a lot of forms) and add them as the new group of elfeed-summary.

Thanks for the useful package.

**Comment by SqrtMinusOne** [comment]
Sound nice. I also use `elfeed-org`, so it would make sense to have a single source of that information. At least in some part. 

I think about something like this. Given this structure in the `elfeed-org` file:
```org
* Header 1
  * Header 2
    * feed_1
    * feed_2
```
Create the same structure in `elfeed-summary`:

- Header 1 (group)
  - Header 2 (group)
    - feed_1
    - feed_2

Or please clarify if you mean something else.

**Comment by jarifuri** [comment]
> Or please clarify if you mean something else.

Your proposal was also my first thought. E.g. mirroring the structure of the `elfeed-org` file.

My second though is below because a feed could have multiple tags.  From `elfeed-org`:
```
* Header 1
** Header 2 :tagA:
*** feed_1 
*** feed_2 :tagC:
** Header 3 :tagB:
*** feed_3 :tagC:
```
Create this structure in the `elfeed-summary`:
- Tags from elfeed-org (group)
  - tagA
  - tagB
  - tagC

Both is possible, I incline more to tags approach because I frequently assign multiple tags.

**Comment by VVialard** [comment]
Hello !
I would also find such a functionality really useful ! I am more leaning toward the first solution nonetheless...
Do any of you guys have sufficient experience in Elisp ? I would really like to help, but I have never used this language extensively...

**Comment by SqrtMinusOne** [comment]
I've added something like this in https://github.com/SqrtMinusOne/elfeed-summary/pull/10. Described the new options in the corresponding section of the [README](https://github.com/SqrtMinusOne/elfeed-summary#automatic-generation-of-groups).

The new `auto-tags` element attempts to create a tree from tags, which can be used to reproduce the structure from `elfeed-org`, as in the first proposal. `tag-groups` works more like the second proposal.

@VVialard this indeed involves recursion, PRs are welcome if have any ideas. The package, however, turned out to be a rather complex one, so it might not be the best starting point.
